{
 "title": "Curated",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (trigger_name) (\n  rate(splice_trigger_latency_duration_seconds_sum[5m])\n)\n/\nsum by (trigger_name) (\n  rate(splice_trigger_latency_duration_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(time() * 1000 - splice_store_last_ingested_record_time_ms{node_name=\"validator_backend\"}) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last_ingested_record_time_ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - splice_store_last_ingested_record_time_ms / 1000) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last_ingested_record_time_ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_store_last_ingested_record_time_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "traffic_control_event_rejected_cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_client_traffic_control_event_rejected_cost",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "splice_store_signal_when_ingested_latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_store_signal_when_ingested_latency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(splice_store_signal_when_ingested_latency_duration_seconds_bucket{node_name=\"validator_backend\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(splice_store_ingested_tx_log_entries_total{node_name=\"validator_backend\"}[5m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_store_ingested_tx_log_entries_total{node_name=\"validator_backend\"}",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "store_confirmation_requests_max_rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_domain_params_store_confirmation_requests_max_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "locked_amulet_balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_wallet_locked_amulet_balance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "topology_num_parties",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_synchronizer_topology_num_parties",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "unlocked_amulet_balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_wallet_unlocked_amulet_balance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "num_parties_per_participant",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_synchronizer_topology_num_parties_per_participant",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "earliest_aggregated_round",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_scan_store_earliest_aggregated_round",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}