{
 "title": "Celestia Bridge dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(otel_celestia_bridge_hdr_store_head_height_gauge,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "otel_celestia_bridge_runtime_uptime_milliseconds_total{env=\"$env\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "otel_celestia_bridge_build_info{env=\"$env\"}",
     "legendFormat": "{{semantic_version}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_celestia_bridge_hdr_store_head_height_gauge{env=\"$env\"}",
     "legendFormat": "Block Height"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(otel_celestia_bridge_hdr_store_head_height_gauge{env=\"$env\"}[5m])",
     "legendFormat": "Block Height Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_celestia_bridge_full_discovery_amount_of_peers{env=\"$env\"}",
     "legendFormat": "Total Peers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_celestia_bridge_archival_discovery_amount_of_peers{env=\"$env\"}",
     "legendFormat": "Archival Peers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_celestia_bridge_hdr_sync_subjective_head_gauge{env=\"$env\"} - otel_celestia_bridge_hdr_store_head_height_gauge{env=\"$env\"}",
     "legendFormat": "Blocks To Sync"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(otel_celestia_bridge_hdr_sync_subjective_head_gauge{env=\"$env\"}[10m]))/10",
     "legendFormat": "Blocks per minute"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "increase(otel_celestia_bridge_hdr_sync_subjective_head_gauge{env=\"$env\"}[10m])/10",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Store Put Latency Distribution [1h]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(otel_celestia_bridge_eds_store_put_time_histogram_sum{env=\"$env\"}[60m]) / rate(otel_celestia_bridge_eds_store_put_time_histogram_count{env=\"$env\"}[60m])",
     "legendFormat": "eds_size={{eds_size}}"
    }
   ]
  },
  {
   "title": "Store Put Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(otel_celestia_bridge_eds_store_put_time_histogram_sum{env=\"$env\"}[5m])",
     "legendFormat": "eds_size={{eds_size}}"
    }
   ]
  },
  {
   "title": "Store Put Operations / Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "rate(otel_celestia_bridge_eds_store_put_time_histogram_count{env=\"$env\"}[5m]) * 60",
     "legendFormat": "eds_size={{eds_size}}"
    }
   ]
  },
  {
   "title": "Sent shrex/nd responses / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(otel_celestia_bridge_shrex_nd_server_responses_total{env=\"$env\"}[60m])*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Sent shrex/eds responses / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(otel_celestia_bridge_shrex_eds_server_responses_total{env=\"$env\"}[60m])*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Number of headers served",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "otel_celestia_bridge_hdr_p2p_exch_srvr_headers_served_counter_total{env=\"$env\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total header message count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "otel_celestia_bridge_hdr_p2p_sub_msg_num_counter_total{env=\"$env\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Info",
     "expr": "(sum by(level) (count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} |~ `(?i)inf` [$__auto])) * 100) / sum(count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} [$__auto]))",
     "legendFormat": "Info",
     "scenarioId": "INFO"
    },
    {
     "alias": "Error",
     "expr": "(sum by(level) (count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} |~ `(?i)err` [$__auto])) * 100) / sum(count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} [$__auto]))",
     "legendFormat": "Error",
     "scenarioId": "ERROR"
    },
    {
     "alias": "Debug",
     "expr": "sum by (level) (count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} |~  `(?i)deb` [$__auto])) / (sum(count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} [$__auto]))) * 100",
     "legendFormat": "Debug",
     "scenarioId": "DEBUG"
    },
    {
     "alias": "Warn",
     "expr": "sum by (level) (count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} |~  `(?i)war` [$__auto])) / (sum(count_over_time({env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} [$__auto]))) * 100",
     "legendFormat": "Warn",
     "scenarioId": "WARN"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{env=\"$env\", filename=\"/opt/celestia-bridge/log/celestia-bridge.log\"} |= ``"
    }
   ]
  }
 ]
}