{
 "title": "EigenDA",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_registered_quorums_rank,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rank by TVL in Quorums",
   "type": "stat",
   "description": "1 being the highest.\n\n0 - you are not opted in that quorum",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_registered_quorums_rank{env=\"$env\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Stake Share in Quorums (In Basis Points)",
   "type": "timeseries",
   "description": "Divide by 100 to get %age stake.\n\n0 for a quorum means you are opted out of that quorum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_registered_quorums_stake_share{env=\"$env\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "description": "Display reachability status of the node",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_reachability_status{env=\"$env\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Socket updates",
   "type": "stat",
   "description": "the total number of node's socket address updates",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_eigenda_node_socket_updates_total{env=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "V1 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Signing Rate",
   "type": "stat",
   "description": "Number of signed / Number of received batches\nThis metrics doesn't account for batches you did not receive due to any connectivity issues",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * 100 / $B", "type": "math" }
   ]
  },
  {
   "title": "Average processed batch size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_eigenda_processed_batches_total{exported_type=\"size\", env=\"$env\"})\n/\nsum(node_eigenda_processed_batches_total{exported_type=\"number\", env=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch by status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (node_eigenda_processed_batches_total{exported_type=\"number\", env=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA number of processed batches",
   "type": "timeseries",
   "description": "the total number of batches processed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{exported_type=\"number\", env=\"$env\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "EigenDA size of processed batches",
   "type": "timeseries",
   "description": "the total size of batches processed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{exported_type=\"size\", env=\"$env\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of EigenDA Blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_eigenda_blobs_total{exported_type=\"number\", env=\"$env\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Size of EigenDA Blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_eigenda_blobs_total{exported_type=\"size\", env=\"$env\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "EigenDA StoreChunks RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_eigenda_rpc_requests_total{method=\"StoreChunks\", env=\"$env\"}[$__range])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Latency StoreChunks (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_request_latency_ms{quantile=\"0.99\", method=\"StoreChunks\", env=\"$env\"}",
     "legendFormat": "p99 {{stage}}"
    },
    {
     "expr": "node_request_latency_ms{quantile=\"0.95\", method=\"StoreChunks\", env=\"$env\"}",
     "legendFormat": "p95 {{stage}}"
    }
   ]
  },
  {
   "title": "EigenDA size of removed batches",
   "type": "timeseries",
   "description": "the total size of batches that have been removed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{exported_type=\"size\", status=\"removed\", env=\"$env\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA number of removed batches",
   "type": "timeseries",
   "description": "the total number  of batches that have been removed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "node_eigenda_removed_batches_total{exported_type=\"number\", status=\"removed\", env=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "V2 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "EigenDA V2 RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_service=~\"validator.(Dispersal|Retrieval)\", env=\"$env\"}[3m])",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(eigenda_node_store_chunks_request_size_bytes{env=\"$env\"})",
     "legendFormat": "Store Chunks"
    }
   ]
  },
  {
   "title": "EigenDA V2 RPC Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_service=~\"validator.(Dispersal|Retrieval)\", grpc_code=\"OK\", env=\"$env\"}[3m])",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 RPC Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_service=~\"validator.(Dispersal|Retrieval)\", grpc_code=\"Internal\", env=\"$env\"}[3m])",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Average Store Chunks Latency by Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum by (stage) (\n    rate(\n      eigenda_node_store_chunks_stage_latency_ms_sum{env=\"$env\"}[5m]\n    )\n  )\n)\n/\n(\n  sum by (stage) (\n    rate(\n      eigenda_node_store_chunks_stage_latency_ms_count{env=\"$env\"}[5m]\n    )\n  )\n)\n",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks p50 Latency By Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (stage) (\n    eigenda_node_store_chunks_stage_latency_ms{\n      quantile=\"0.5\", env=\"$env\"\n    }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks p90 Latency By Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (stage) (\n    eigenda_node_store_chunks_stage_latency_ms{\n      quantile=\"0.9\", env=\"$env\"\n    }\n)\n",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks p99 Latency By Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (stage) (\n    eigenda_node_store_chunks_stage_latency_ms{quantile=\"0.99\", env=\"$env\"}\n)\n",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Get Chunks Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(eigenda_node_get_chunks_latency_ms{env=\"$env\"}) by (quantile)",
     "legendFormat": "p{{quantile}}"
    }
   ]
  }
 ]
}