{
 "title": "Obol",
 "description": "Looks at a specific cluster only",
 "tags": [ "Cluster" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(app_monitoring_readyz,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "description": "Successful cluster duty percentage by type over the whole time range",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(increase(core_tracker_success_duties_total{env=\"$env\"}[$__range])) by (duty,env)\n) \n/ \n( \n    sum(increase(core_tracker_expect_duties_total{env=\"$env\"}[$__range])) by (duty,env) \n) > 0",
     "legendFormat": "Cluster Duty Success(%)  {{duty}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Average beacon node score for the whole time window. The score is a combination of:\n - **errors**: the ratio or errors returned by the beacon node \n - **latency**: how fast or slow the beacon node is responding\n\n\nThe performance of the Beacon node is critical to the performance of the validators and therefore rewards.  ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    (\n0.5 * (1.0 - 10*(sum(increase(app_eth2_errors_total{env=\"$env\"}[5m])) / (sum(increase(app_eth2_latency_seconds_count{env=\"$env\"}[5m]))))) OR on() vector(0.5)\n    )\n    +\n    (\n        0.5 * (1.0 - clamp_max(histogram_quantile(0.99, sum(rate(app_eth2_latency_seconds_bucket{env=\"$env\"}[5m])) by (le)),1))\n    )\n)",
     "legendFormat": "Beacon Node Score"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "stat",
   "description": "Status returned from the `/readyz` health status endpoint. Unhealthy reasons include beacon node problems, charon p2p problems, or validator client problems.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_readyz{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Cluster Info",
   "type": "stat",
   "description": "Information about the charon cluster.\n\n- **Network**: The blockchain network \n- **Operators/Nodes**: The number of operators or nodes or peers in the charon DV cluster.\n- **Threshold**: The minimum number of participating nodes (also quorum).\n- **Validators**: The number of validators added to the cluster, each validator is staking 32 ETH. ",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_operators{env=\"$env\"}",
     "legendFormat": "Operators/Nodes"
    },
    {
     "expr": "cluster_threshold{env=\"$env\"}",
     "legendFormat": "Threshold"
    },
    {
     "expr": "core_scheduler_validators_active{env=\"$env\"}",
     "legendFormat": "Validators Active"
    },
    {
     "expr": "cluster_validators{env=\"$env\"}",
     "legendFormat": "Validators Total"
    }
   ]
  },
  {
   "title": "Beacon Node Version",
   "type": "table",
   "description": "Number of charon nodes running particular consensus client versions",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "max(app_beacon_node_version{env=\"$env\"}) by (cluster_name, cluster_hash, cluster_peer, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Client Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "count(core_validatorapi_vc_user_agent{env=\"$env\"}) by (cluster_peer, user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Connectivity and Missed Duties (🚧)",
   "type": "table",
   "description": "- **Peer**: The peer's name (inferred from their *charon-enr-private-key*)\n- **You**: ⭐️ is this local charon node\n- **Connected**: Whether you are currently connected to this peer.\n- **Direct**: Whether the connection is *direct* (👍) or *relay* (👎) \n- **Latency**: The time messages take to travel to/from the peer.\n- **Version**: The version of the peer's charon node\n- **Supported**: Whether the peers charon version is supported/compatible or not.\n- **Uptime**\" The duration since peer was restarted.\n- **🚧Attest**: Number of attestation duties missed in the time window.\n- **🚧Propose**: Number of block proposal duties missed in the time window.\n- **🚧Other**: Number of other duties missed in the time window.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(p2p_ping_success{env=\"$env\"}) by (peer)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{env=\"$env\"}[$__rate_interval])) by (le,peer))  * 1000"
    },
    {
     "expr": "sum(p2p_ping_success{env=\"$env\"}) by (peer)"
    },
    {
     "expr": "(max(p2p_peer_connection_types{exported_type=\"direct\", env=\"$env\"}) by (peer)*10 + \nmax(p2p_peer_connection_types{exported_type=\"relay\", env=\"$env\"}) by (peer))"
    },
    {
     "expr": "sum(app_peerinfo_version{env=\"$env\"}) by (peer,version) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(app_peerinfo_start_time_secs{env=\"$env\"} > 0) by (peer)"
    },
    {
     "expr": "max(app_peerinfo_index{env=\"$env\"}) by (peer)"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{duty=\"attester\", env=\"$env\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{duty=\"attester\", env=\"$env\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{duty=~\".*proposer\", env=\"$env\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{duty=~\".*proposer\", env=\"$env\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{duty!~\"(proposer|attester)\", env=\"$env\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{duty!~\"(proposer|attester)\", env=\"$env\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(app_peerinfo_version_support{env=\"$env\"}) by (peer) "
    },
    {
     "expr": "sum(app_peerinfo_nickname{env=\"$env\"}) by (peer,peer_nickname)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Versions and Git Hashes",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(app_version{env=\"$env\"}) by (version)",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "max(app_git_commit{env=\"$env\"}) by (git_hash)",
     "legendFormat": "{{git_hash}}"
    },
    {
     "expr": "rate(app_start_time_secs{env=\"$env\"}[5m]) > 0",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Historical Health Status",
   "type": "timeseries",
   "description": "Status returned from the `/readyz` health status endpoint. Unhealthy reasons include beacon node problems, charon p2p problems, or validator client problems.",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(app_monitoring_readyz{env=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Connections (🟢=direct, 🟡=relay, 🔴=not connected)",
   "type": "state-timeline",
   "description": "Type of connections to each peer in the cluster during the time window:\n - 🟢 Green: Direct connection (this is the preferred)\n - 🟡 Yellow: Indirect relay connection (this is ok if only temporary)\n - 🔴 Red: No connection to peer (this is a problem)\n\nSee https://docs.obol.tech/docs/charon/networking#external-p2p-network",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "(max(p2p_ping_success{env=\"$env\"}) by (peer))\n+\n(1 * max(p2p_peer_connection_types{exported_type=\"relay\", env=\"$env\"}) by (peer))\n+ \n(100 * max(p2p_peer_connection_types{exported_type=\"direct\", env=\"$env\"}) by (peer))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - max(app_start_time_secs{env=\"$env\"})",
     "legendFormat": "Uptime"
    },
    {
     "expr": "core_scheduler_current_slot{env=\"$env\"}",
     "legendFormat": "Slot"
    },
    {
     "expr": "core_scheduler_current_epoch{env=\"$env\"}",
     "legendFormat": "Epoch"
    },
    {
     "expr": "core_scheduler_validators_active{env=\"$env\"}",
     "legendFormat": "Validators Active"
    },
    {
     "expr": "sum(p2p_ping_success{env=\"$env\"})",
     "legendFormat": "Charon Peers Connected"
    },
    {
     "expr": "sum(p2p_relay_connections{env=\"$env\"}) ",
     "legendFormat": "Relays Connected"
    },
    {
     "expr": "app_beacon_node_peers{env=\"$env\"}",
     "legendFormat": "Beacon Node Peers"
    },
    {
     "expr": "p2p_reachability_status{env=\"$env\"}",
     "legendFormat": "P2P Reachability"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "table",
   "description": "Status and balance of each validator by public key with links to beaconcha.in.\n\nIf present, the \"❗️Peer Exits\" column indicate the number of peers that submitted partially signed exits for each validator.",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 30 },
   "targets": [
    {
     "expr": "max(core_scheduler_validator_balance_gwei{env=\"$env\"} / 1000000000) by (pubkey_full,pubkey, cluster_network)",
     "legendFormat": "{{pubkey}}"
    },
    {
     "expr": "max(core_scheduler_validator_status{env=\"$env\"} == 1) by (pubkey, status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(core_parsigdb_exit_total{env=\"$env\"}) by (pubkey) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning(w) and Error(e) logs (per 2m)",
   "type": "timeseries",
   "description": "Warning (w) and error (e) logs grouped by topic. \n\nOccasional warns and errors are normal, but a significant increase indicate problems that require operators to investigate by looking at the actual logs entries.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(app_log_error_total[2m])) by (topic) > 0 ",
     "legendFormat": "e:{{topic}}"
    },
    {
     "expr": "sum(increase(app_log_warn_total[2m])) by (topic) > 0 ",
     "legendFormat": "w:{{topic}}"
    }
   ]
  },
  {
   "title": "Connection Types - direct or relay",
   "type": "table",
   "description": "A 2D view of whether the connection between peers is direct (🟢) or relay (🔴)",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "(max(p2p_peer_connection_types{cluster_name=\"Lido x Obol: Zephyr Zorilla\",cluster_hash=\"9b98bb8\",exported_type=\"direct\", env=\"$env\"}) by (cluster_peer, peer, env)*10 + \nmax(p2p_peer_connection_types{cluster_name=\"Lido x Obol: Zephyr Zorilla\",cluster_hash=\"9b98bb8\",exported_type=\"relay\", env=\"$env\"}) by (cluster_peer, peer, env))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer latencies 2D",
   "type": "table",
   "description": "A two dimensional view of 90th percentile latencies between peers that report to us and their cluster operators.",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{env=\"$env\"}[5m])) by (le,cluster_peer,peer))  * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Duties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "✅ Completed duties by type ",
   "type": "status-history",
   "description": "Completed duties by type over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(increase(core_bcast_broadcast_total{env=\"$env\"}[2m])) by (duty) > 0",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "✅ Successful Peer Participation: Duty=All",
   "type": "status-history",
   "description": "Successful duty participation per peer (filtered by selected duty) over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(core_tracker_participation_total{env=\"$env\"}[5m])) by (peer) > 0 ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "❌ Failed duties by type (per 2m)",
   "type": "status-history",
   "description": "Failed duties by type over time. Use data link to show logs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(core_tracker_failed_duties_total[2m])) by (duty) > 0",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "🚧 Missed Peer Participation: Duty=All",
   "type": "status-history",
   "description": "Missed duty participation per peer (filtered by selected duty) over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(core_tracker_participation_missed_total[2m])) by (peer) > 0 ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "❌ Failed duty percentage by type (per 5m)",
   "type": "timeseries",
   "description": "Failed duties percentage by type over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(increase(core_tracker_failed_duties_total[5m])) by (duty)\n) \n/ \n(\n    sum(increase(core_tracker_failed_duties_total[5m])) by (duty) \n    + \n    sum(increase(core_bcast_broadcast_total[5m])) by (duty) \n) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "🚧 Missed Peer Participation",
   "type": "status-history",
   "description": "Missed duty participation per duty (filtered by peer) over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "repeat": "peer",
   "targets": [
    {
     "expr": "sum(rate(core_tracker_participation_missed_total[5m])) by (duty) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "🚨 Duty failure reason: All (per 5m)",
   "type": "timeseries",
   "description": "Number of failed duties by reason per time window. Note this is only available from v0.16.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(core_tracker_failed_duty_reasons_total[5m])) by (reason) > 0 ",
     "legendFormat": "{{.duty}}"
    }
   ]
  },
  {
   "title": "Consensus duration: All",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.90, increase(core_consensus_duration_seconds_bucket[5m]))) by (timer)",
     "legendFormat": "{{timer}}"
    }
   ]
  },
  {
   "title": "💥 Broadcasted duties never included on-chain (per 5m)",
   "type": "timeseries",
   "description": "Duties that was successfully broadcast to the Beacon Node, but that was never included on-chain. This could be due to broadcasting too late (too slow), but it could also just be to aspects of consensus layer out-of-our-control. See https://eth2book.info/bellatrix/part2/incentives/rewards/#remarks.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(increase(core_tracker_inclusion_missed_total[5m])) by (duty)) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Broadcast delay: All",
   "type": "timeseries",
   "description": "The delay after the start of the slot when the duty was successfully broadcasted. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.90, rate(core_bcast_broadcast_delay_seconds_bucket[5m]))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    {
     "expr": "sum(core_tracker_inclusion_delay)",
     "legendFormat": "Instant"
    },
    {
     "expr": "max(avg_over_time(core_tracker_inclusion_delay[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Consensus Rounds: All",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "max(core_consensus_decided_rounds) by (timer)",
     "legendFormat": "{{timer}}"
    }
   ]
  },
  {
   "title": "🚨 Consensus Timeouts (per 5m)",
   "type": "timeseries",
   "description": "Number of consensus timeouts per time window.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(increase(core_consensus_timeout_total{exported_duty=~\"$duty\"}[5m])) by (timer) > 0",
     "legendFormat": "{{.duty}}"
    }
   ]
  },
  { "title": "Upstream Beacon Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "(\n  sum(app_beacon_node_version) by (version)\n)\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Node API requests rate",
   "type": "timeseries",
   "description": "Upstream beacon node API request rate per second by endpoint",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(app_eth2_latency_seconds_count[5m])) by (endpoint) > 0 ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Beacon Node API request latency (90%)",
   "type": "timeseries",
   "description": "Upstream beacon node API request latency (90th percentile) by endpoint by timewindow",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_eth2_latency_seconds_bucket[5m])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of consensus layer P2P peers the beacon node is connected to",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_beacon_node_peers{env=\"$env\"}",
     "legendFormat": "Beacon node peers"
    }
   ]
  },
  { "title": "Downstream Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Validator API requests rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(core_validatorapi_request_latency_seconds_count[5m])) by (endpoint) > 0",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Validator API request latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(core_validatorapi_request_latency_seconds_bucket[5m])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "🚨 Validator API error count (per 5m)",
   "type": "timeseries",
   "description": "Number of errors per endpoint per time window",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(increase(core_validatorapi_request_error_total[5m])) by (endpoint) > 0 ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "P2P Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Peer Connections (🟢=direct, 🟡=relay, 🔴=not connected)",
   "type": "state-timeline",
   "description": "Type of connections to each peer in the cluster during the time window:\n - 🟢 Green: Direct connection (this is the preferred)\n - 🟡 Yellow: Indirect relay connection (this is ok if only temporary)\n - 🔴 Red: No connection to peer (this is a problem)\n\nSee https://docs.obol.tech/docs/charon/networking#external-p2p-network",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "(max(p2p_ping_success) by (peer))\n+\n(1 * max(p2p_peer_connection_types{exported_type=\"relay\"}) by (peer))\n+ \n(100 * max(p2p_peer_connection_types{exported_type=\"direct\"}) by (peer))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer ping latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket[5m])) by (le,peer))  ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Ping Errors",
   "type": "state-timeline",
   "description": "Time windows that contain ping errors per peer",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "sum(increase(p2p_ping_error_total[5m])) by (peer) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New P2P Connections (per 5m)",
   "type": "timeseries",
   "description": "Number of new libp2p connections per peer per time window",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(increase(p2p_peer_connection_total[5m])) by (peer) > 0 ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Peer ping latency (90%) (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket[5m])) by (le,peer))",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Ping Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(p2p_ping_latency_secs_count[5m])) by (peer) ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "P2P Network Avg Rate Rx+Tx",
   "type": "timeseries",
   "description": "Avg Rate of P2P network bytes sent plus received per peer (bytes/second) ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(p2p_peer_network_receive_bytes_total[5m])) by (peer) + sum(rate(p2p_peer_network_sent_bytes_total[5m])) by (peer)",
     "legendFormat": "{{ peer }}"
    }
   ]
  },
  {
   "title": "Clock Offset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_peerinfo_clock_offset_seconds{cluster_peer=~\"cloudy-game\", env=\"$env\"}) by (peer) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Network Bytes Rx+Tx (per 5m)",
   "type": "timeseries",
   "description": "Total P2P network bytes sent plus received per peer per time window (bytes per interval)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(p2p_peer_network_receive_bytes_total{env=\"$env\"}[5m])) by (peer) + sum(increase(p2p_peer_network_sent_bytes_total{env=\"$env\"}[5m])) by (peer)",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Connected Relays",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "sum(p2p_relay_connections{env=\"$env\"}) by (peer) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active libp2p streams",
   "type": "timeseries",
   "description": "The number of active libp2p streams by peer or relay. Note this can be further grouped by direction and protocol.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(p2p_peer_streams{env=\"$env\"}) by (peer)",
     "legendFormat": "{{peer}}"
    }
   ]
  }
 ]
}