{
 "title": "Process Exporter",
 "description": "Dashboard for monitoring Linux processes.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "server",
    "query": {
     "query": "label_values(process_exporter_build_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(process_exporter_build_info,instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "query_result(\"$server:$port\")"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(process_exporter_build_info,job)"
    }
   },
   { "name": "port_node_exporter", "query": "9100" }
  ]
 },
 "panels": [
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "Утилизация CPU (%) процессом.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(irate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$host\", job=\"$job\"}[$__rate_interval])) by (groupname) > 0) / scalar(count(count(node_cpu_seconds_total{instance=\"$server:$port_node_exporter\", job=\"node_exporter\"}) by (cpu)))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Resident Memory %",
   "type": "timeseries",
   "description": "Фактическое использование памяти (%) процессом.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(namedprocess_namegroup_memory_bytes{instance=~\"$host\", memtype=\"resident\", job=\"$job\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0) / (namedprocess_namegroup_memory_bytes{instance=~\"$host\", memtype=\"virtual\", job=\"$job\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU (millicore)",
   "type": "timeseries",
   "description": "Утилизация CPU (millicore) процессом.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(irate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$host\", job=\"$job\"}[$__rate_interval])) by (groupname) > 0) * 1000",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "description": "Фактическое использование памяти процессом.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$host\", memtype=\"resident\", job=\"$job\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Number Threads",
   "type": "timeseries",
   "description": "Количество потоков.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_threads{instance=~\"$host\", job=\"$job\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "description": "Общий объем памяти, который может потребоваться процессу.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$host\", memtype=\"virtual\", job=\"$job\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Voluntary Context Switches",
   "type": "timeseries",
   "description": "Добровольное переключение контекста.  \nПроисходит, когда поток выполняет запись в IO или запрашивает ресурс, который недоступен.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=~\"$host\", ctxswitchtype=\"voluntary\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Nonvoluntary Context Switches",
   "type": "timeseries",
   "description": "Непроизвольное переключение контекста.  \nПроисходит, когда поток превышает временной интервал, назначенный планировщиком.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=~\"$host\", ctxswitchtype=\"nonvoluntary\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Group File Descriptors",
   "type": "timeseries",
   "description": "Количество открытых файловых дескрипторов для группы.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{instance=~\"$host\", job=\"$job\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Total File Descriptors",
   "type": "timeseries",
   "description": "USED - Количество открытых файловых дескрипторов.  \nMAX - Максимальное количество открытых файловых дескрипторов.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "process_max_fds{instance=~\"$host\", job=\"$job\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": " Read Bytes",
   "type": "timeseries",
   "description": "Количество байтов, прочитанных группой.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{instance=~\"$host\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "description": "Количество байтов, записанных группой.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{instance=~\"$host\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Minor Page Faults",
   "type": "timeseries",
   "description": "Незначительные ошибки страницы памяти.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_minor_page_faults_total{instance=~\"$host\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Major Page Faults",
   "type": "timeseries",
   "description": "Основные ошибки страницы памяти.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_major_page_faults_total{instance=~\"$host\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Number Processes",
   "type": "timeseries",
   "description": "Количество процессов в группе.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{instance=~\"$host\", job=\"$job\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Processes Uptime",
   "type": "table",
   "description": "Группы процессов - Начало работы - Время работы.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "time() - (namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$host\", job=\"$job\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}