{
 "title": "Solana Monitoring",
 "tags": [
  "prometheus",
  "solana"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(solana_network_epoch,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_val_skip_rate{env=\"$env\"}",
     "legendFormat": "Skip Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{env=\"$env\"}",
     "legendFormat": "Identity account Balance"
    }
   ]
  },
  {
   "title": "Leader Slots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(solana_val_total_leader_slots{env=\"$env\"}[2m])",
     "legendFormat": "{{label_name}}Total"
    },
    {
     "expr": "last_over_time(solana_val_blocks_produced{env=\"$env\"}[2m])",
     "legendFormat": "{{label_name}}Produced"
    },
    {
     "expr": "last_over_time(solana_val_skipped_slots{env=\"$env\"}[2m])",
     "legendFormat": "{{label_name}}Skipped"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_active_validators{state=\"current\", env=\"$env\"}",
     "legendFormat": "{{label_name}}Current"
    },
    {
     "expr": "solana_active_validators{state=\"delinquent\", env=\"$env\"}",
     "legendFormat": "{{label_name}}Delinquent"
    }
   ]
  },
  {
   "title": "Validator Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_activated_stake{env=\"$env\"}",
     "legendFormat": "Validator stake, SOL"
    },
    {
     "expr": "solana_val_commission{env=\"$env\"}",
     "legendFormat": "Commision, %"
    }
   ]
  },
  {
   "title": "Next Leader Slot",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(solana_current_slot{env=\"$env\"} - solana_previous_leader_slot{env=\"$env\"}) * 100/(solana_next_leader_slot{env=\"$env\"} - solana_previous_leader_slot{env=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_total_slots{env=\"$env\"}",
     "legendFormat": "{{label_name}}Total leader slots"
    },
    {
     "expr": "solana_total_blocks_produced{env=\"$env\"}",
     "legendFormat": "{{label_name}}Produced"
    },
    {
     "expr": "solana_skipped_total{env=\"$env\"}",
     "legendFormat": "{{label_name}}Skipped"
    }
   ]
  },
  {
   "title": "Epoch Progress",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(solana_slot_index{env=\"$env\"}*100)/solana_slot_in_epoch{env=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_network_epoch{env=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_health{status=\"healthy\", env=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"solana-logs\", level=\"ERROR\"}[$__auto]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_next_slot_time{env=\"$env\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "Amplifier Votes",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "columns": [
      { "selector": "cluster", "text": "Cluster", "type": "string" },
      { "selector": "epoch", "text": "Epoch", "type": "string" },
      { "selector": "agave_min_version", "text": "Min Version", "type": "string" },
      { "selector": "agave_max_version", "text": "Max Version", "type": "string" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api.solana.org/api/community/v1/sfdp_required_versions?cluster=mainnet-beta",
     "url_options": { "body_content_type": "application/json", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(1, solana_node_version{env=\"$env\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Amplifier Votes",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "columns": [
      { "selector": "cluster", "text": "Cluster", "type": "string" },
      { "selector": "epoch", "text": "Epoch", "type": "string" },
      { "selector": "agave_min_version", "text": "Min Version", "type": "string" },
      { "selector": "agave_max_version", "text": "Max Version", "type": "string" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api.solana.org/api/community/v1/sfdp_required_versions?cluster=testnet",
     "url_options": { "body_content_type": "application/json", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Active/Delinquent Stake, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_delinquent_stake{env=\"$env\"}*100/solana_active_stake{env=\"$env\"}",
     "legendFormat": "{{label_name}}Delinquent"
    }
   ]
  },
  { "title": "Skip Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Skip Rate - Validator",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_val_skip_rate{env=\"$env\"}",
     "legendFormat": "{{label_name}}Validator Skip Rate"
    },
    {
     "expr": "solana_net_skip_rate{env=\"$env\"}",
     "legendFormat": "{{label_name}} Network Skip Rate"
    }
   ]
  },
  {
   "title": "Skip Rate - Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_net_skip_rate{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Skip Rate - Difference",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 36 },
   "targets": [
    {
     "expr": "solana_skip_rate_diff{env=\"$env\"}"
    }
   ]
  },
  { "title": "Vote Credits, Tx/sec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Vote Credits/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(solana_vote_credits{env=\"$env\"}[15m])",
     "legendFormat": "{{label_name}}Credits"
    }
   ]
  },
  {
   "title": "TX/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(solana_tx_count{env=\"$env\"}[15m])",
     "legendFormat": "{{label_name}}Transactions"
    }
   ]
  },
  {
   "title": "Average slot duration, sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "solana_avg_slot_duration{env=\"$env\"}",
     "legendFormat": "{{label_name}}Duration, sec"
    }
   ]
  },
  { "title": "Vote Height", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Slot Difference",
   "type": "timeseries",
   "description": "val_slot - net_slot",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "solana_slot_diff{env=\"$env\"}",
     "legendFormat": "{{label_name}}Slot Difference"
    }
   ]
  },
  {
   "title": "Block Height Difference",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "solana_block_height_diff{env=\"$env\"}",
     "legendFormat": "{{label_name}}Block Height Difference"
    }
   ]
  },
  {
   "title": "Vote Height Difference",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "solana_vote_height_diff{env=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vote Height - Validator",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "solana_validator_vote_height{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Vote Height - Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "solana_network_vote_height{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Validator Credits in Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "solana_vote_credits{env=\"$env\"}",
     "legendFormat": "{{label_name}}Credits"
    }
   ]
  },
  { "title": "Diff slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Max Retransmit Slot Difference",
   "type": "timeseries",
   "description": "Val - Net",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "max(\n  (solana_val_max_retransmit_slot{env=\"$env\"} - solana_net_max_retransmit_slot{env=\"$env\"}) \n  and (solana_val_max_retransmit_slot{env=\"$env\"} > 0) \n  and (solana_net_max_retransmit_slot{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Slot"
    }
   ]
  },
  {
   "title": "Max Shred Insert Slot Difference",
   "type": "timeseries",
   "description": "Val - Net",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "max(\n  (solana_val_max_shred_insert_slot{env=\"$env\"} - solana_net_max_shred_insert_slot{env=\"$env\"}) \n  and (solana_val_max_shred_insert_slot{env=\"$env\"} > 0) \n  and (solana_net_max_shred_insert_slot{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Slot"
    }
   ]
  },
  {
   "title": "Validator/Cluster Vote Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "max(\n  (solana_vote_credits{env=\"$env\"}*100/solana_total_slots{env=\"$env\"}) \n  and (solana_vote_credits{env=\"$env\"} > 0) \n  and (solana_total_slots{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Validator Vote, %"
    },
    {
     "expr": "max(\n  (solana_avg_vote_credits{env=\"$env\"}*100/solana_total_slots{env=\"$env\"}) \n  and (solana_avg_vote_credits{env=\"$env\"} > 0) \n  and (solana_total_slots{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Network Vote, %"
    }
   ]
  },
  {
   "title": "Vote Credits Compare to Cluster Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  (solana_vote_credits{env=\"$env\"}*100/solana_total_slots{env=\"$env\"}) \n  and (solana_vote_credits{env=\"$env\"} > 0) \n  and (solana_total_slots{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Validator Vote, %"
    },
    {
     "expr": "max(\n  (solana_avg_vote_credits{env=\"$env\"}*100/solana_total_slots{env=\"$env\"}) \n  and (solana_avg_vote_credits{env=\"$env\"} > 0) \n  and (solana_total_slots{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Network Vote, %"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Vote Credits Compare to Cluster Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  (solana_vote_credits{env=\"$env\"}*100/solana_total_slots{env=\"$env\"}) \n  and (solana_vote_credits{env=\"$env\"} > 0) \n  and (solana_total_slots{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Validator Vote, %"
    },
    {
     "expr": "max(\n  (solana_avg_vote_credits{env=\"$env\"}*100/solana_total_slots{env=\"$env\"}) \n  and (solana_avg_vote_credits{env=\"$env\"} > 0) \n  and (solana_total_slots{env=\"$env\"} > 0)\n) or vector(0)",
     "legendFormat": "{{label_name}}Network Vote, %"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  }
 ]
}