{
 "title": "SSV",
 "time": { "from": "now-8h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(ssv_p2p_peers_connected,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Validator count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_validator_validators_per_status{cluster=~\"$cluster\", ssv_validator_status!=\"slashed\"}) by (ssv_validator_status)",
     "legendFormat": "{{ssv_validator_status}}"
    },
    {
     "expr": "sum(ssv_validator_validators_per_status{cluster=~\"$cluster\", ssv_validator_status=\"slashed\"}) by (ssv_validator_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Syncer Last Block",
   "type": "stat",
   "description": "This is responsible for syncing SSV network smart contract events.",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_event_syncer_handler_last_processed_block{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Layer Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ssv_el_sync_status{cluster=~\"$cluster\", ssv_el_status=\"ready\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ssv_el_sync_status{cluster=~\"$cluster\", ssv_el_status!=\"ready\"} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Layer Client",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "ssv_el_sync_status{cluster=~\"$cluster\", ssv_el_status=\"ready\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ssv_el_sync_status{cluster=~\"$cluster\", ssv_el_status!=\"ready\"} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Layer Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "ssv_cl_sync_status{cluster=~\"$cluster\", ssv_cl_sync_status=\"synced\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ssv_cl_sync_status{cluster=~\"$cluster\", ssv_cl_sync_status!=\"synced\"} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Layer Client",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "ssv_cl_sync_status{cluster=~\"$cluster\", ssv_cl_sync_status=\"synced\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ssv_cl_sync_status{cluster=~\"$cluster\", ssv_cl_sync_status!=\"synced\"} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections ",
   "type": "stat",
   "description": "If one of these two is very low it might signal that you have issues reaching out other peers, or that other peers can't connect to you.",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_p2p_connections_active{cluster=~\"$cluster\"}) by (ssv_p2p_connection_direction)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Layer Request Duration",
   "type": "heatmap",
   "description": "This is the latency to the Consensus Layer client for all calls. If you want a breakdown of which calls take longer or percentiles, scroll to the `Ethereum Clients` section.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(ssv_cl_request_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Versions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_per_version{cluster=~\"$cluster\"}) by (ssv_node_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted Attestations vs Expected",
   "type": "stat",
   "description": "All validators have to attest once per epoch. We can estimate performance by looking at `active validators` / `submitted attestations by the SSV node`. Submitted attestations have a delay of 1 epoch so if the node was restarted recently it will not have enough information about the first epoch since restart.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_runner_submissions{cluster=~\"$cluster\", ssv_beacon_role=\"ATTESTER\"}) / sum(ssv_validator_validators_per_status{cluster=~\"$cluster\", ssv_validator_status=\"participating\"})",
     "legendFormat": "Submitted Attestations vs Expected %"
    }
   ]
  },
  {
   "title": "Peers ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv_p2p_peers_connected{cluster=~\"$cluster\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Doppelganger Validator Protection",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "validators" } },
   "targets": [
    {
     "expr": "sum(ssv_doppelganger_validators_state{cluster=~\"$cluster\", ssv_doppelganger_validators_unsafe=\"false\"})",
     "legendFormat": "Safe"
    },
    {
     "expr": "sum(ssv_doppelganger_validators_state{cluster=~\"$cluster\", ssv_doppelganger_validators_unsafe=\"true\"}) by ()",
     "legendFormat": "Unsafe"
    }
   ]
  },
  {
   "title": "Connected peers per topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_per_topic{cluster=~\"$cluster\"}) by (ssv_p2p_topic_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted peers per second",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "peers" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_discovery_peers_accepted_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Skipped peers per second",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "peers" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_discovery_peers_skipped_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster, ssv_p2p_discovery_skip_reason)",
       "legendFormat": "{{cluster}} - {{ssv_p2p_discovery_skip_reason}}"
      }
     ]
    },
    {
     "title": "Discovered peers per second",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "peers" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_discovery_peers_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  { "title": "P2P Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Peers connected to per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "(sum(rate(ssv_p2p_connections_connected_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers disconnected from per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "(sum(rate(ssv_p2p_connections_disconnected_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers filtered per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "(sum(rate(ssv_p2p_connections_filtered_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected peer count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_connected{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "Peers connected {{cluster}}"
    },
    {
     "expr": "sum(ssv_p2p_connections_active{cluster=~\"$cluster\"}) by (ssv_p2p_connection_direction, cluster)",
     "legendFormat": "{{ssv_p2p_connection_direction}} peers {{cluster}}"
    }
   ]
  },
  {
   "title": "Connected peers per topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_per_topic{cluster=~\"$cluster\"}) by (ssv_p2p_topic_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected peers per version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_per_version{cluster=~\"$cluster\"}) by (ssv_node_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages per minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 819 },
     "fieldConfig": { "defaults": { "unit": "mpm" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_messages_in_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster) * 60",
       "legendFormat": "in {{cluster}}"
      },
      {
       "expr": "-(sum(rate(ssv_p2p_messages_out_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster) * 60)",
       "legendFormat": "out {{cluster}}"
      }
     ]
    },
    {
     "title": "Stream requests per minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 840 },
     "fieldConfig": { "defaults": { "unit": "mpm" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_stream_requests_received_total{cluster=~\"$cluster\"}[$__rate_interval])) * 60",
       "legendFormat": "received"
      },
      {
       "expr": "-(sum(rate(ssv_p2p_stream_requests_sent_total{cluster=~\"$cluster\"}[$__rate_interval])) * 60)",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Stream responses per minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 840 },
     "fieldConfig": { "defaults": { "unit": "mpm" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_stream_responses_received_total{cluster=~\"$cluster\"}[$__rate_interval])) * 60",
       "legendFormat": "received"
      },
      {
       "expr": "-(sum(rate(ssv_p2p_stream_responses_sent_total{cluster=~\"$cluster\"}[$__rate_interval])) * 60)",
       "legendFormat": "sent"
      }
     ]
    }
   ]
  },
  {
   "title": "P2P Message Validation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Validation Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "mpm" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_message_validations_accepted_total{cluster=~\"$cluster\"}[$__rate_interval])) * 60",
       "legendFormat": "Accepted messages"
      },
      {
       "expr": "sum(rate(ssv_p2p_message_validations_ignored_total{cluster=~\"$cluster\"}[$__rate_interval])) * 60",
       "legendFormat": "Ignored messages"
      },
      {
       "expr": "sum(rate(ssv_p2p_message_validations_rejected_total{cluster=~\"$cluster\"}[$__rate_interval])) * 60",
       "legendFormat": "Rejected messages"
      }
     ]
    },
    {
     "title": "Message Validation Rejected by Reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 820 },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_message_validations_rejected_total{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_p2p_message_validation_discard_reason) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Validation Ignored by Reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 820 },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_message_validations_ignored_total{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_p2p_message_validation_discard_reason) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Validation Duration",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 828 },
     "targets": [
      {
       "expr": "sum(rate(ssv_p2p_message_validations_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Duty Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slot Delay Duration",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 536 },
     "targets": [
      {
       "expr": "sum(rate(ssv_duty_scheduler_slot_ticker_delay_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Duties Scheduled per Role",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 548 },
     "fieldConfig": { "defaults": { "unit": "duties/min" } },
     "targets": [
      {
       "expr": "sum(rate(ssv_duty_scheduler_executions_total{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_runner_role) * 60",
       "legendFormat": "{{ssv_beacon_role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Syncer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last processed block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 537 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_event_syncer_handler_last_processed_block{cluster=~\"$cluster\"}) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Events successfully processed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 537 },
     "targets": [
      {
       "expr": "sum(rate(ssv_event_syncer_handler_events_processed_total{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_event_syncer_event_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event processing failures",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 537 },
     "targets": [
      {
       "expr": "sum(rate(ssv_event_syncer_handler_events_failed_total{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_event_syncer_event_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Runners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Pre Consensus Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_pre_consensus_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_consensus_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Post Consensus Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_post_consensus_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram ATTESTER role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_duty_duration_seconds_bucket{cluster=~\"$cluster\", ssv_runner_role=\"COMMITTEE\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram AGGREGATOR role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_duty_duration_seconds_bucket{cluster=~\"$cluster\", ssv_runner_role=\"AGGREGATOR\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram SYNC COMMITTEE role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_duty_duration_seconds_bucket{cluster=~\"$cluster\", ssv_runner_role=\"SYNC_COMMITTEE_CONTRIBUTION\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram PROPOSER role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_duty_duration_seconds_bucket{cluster=~\"$cluster\", ssv_runner_role=\"PROPOSER\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of submissions per role",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(ssv_runner_submissions{cluster=~\"$cluster\"}) by (ssv_beacon_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of failed submissions per role",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(rate(ssv_runner_submissions_failed_total{cluster=~\"$cluster\"}[5m])) by (ssv_beacon_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 570 },
     "targets": [
      {
       "expr": "sum(rate(ssv_validator_errors_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validators removed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 570 },
     "targets": [
      {
       "expr": "sum(rate(ssv_validator_validators_removed_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validators per status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 632 },
     "targets": [
      {
       "expr": "sum(ssv_validator_validators_per_status{cluster=~\"$cluster\"}) by (ssv_validator_status, cluster)",
       "legendFormat": "{{cluster}} {{ssv_validator_status}}"
      }
     ]
    }
   ]
  },
  { "title": "QBFT Consensus Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Validator Stage Duration per role",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_stage_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_runner_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Stage Duration Per Stage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_stage_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_validator_stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Stage Duration per round",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_stage_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (ssv_validator_duty_round)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethereum Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Layer Syncing Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 578 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_el_sync_status{cluster=~\"$cluster\"} != 0) by (cluster, ssv_el_status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Layer Sync Distance",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 578 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_el_sync_distance{cluster=~\"$cluster\"}) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Layer Last Processed Block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 578 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_el_sync_last_processed_block{cluster=~\"$cluster\"}) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Client Latency (Sync Progress)",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 584 },
     "targets": [
      {
       "expr": "sum(rate(ssv_el_request_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Layer Syncing Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 596 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_cl_sync_status{cluster=~\"$cluster\"} != 0) by (cluster, ssv_cl_sync_status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Layer Sync Distance",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 596 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_cl_sync_distance{cluster=~\"$cluster\"}) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Overall Consensus Layer Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 602 },
     "targets": [
      {
       "expr": "sum(rate(ssv_cl_request_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Layer Successful Request Duration Per Method",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 614 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.90, sum(rate(ssv_cl_request_duration_seconds_bucket{cluster=~\"$cluster\", http_response_error_status_code=\"\"}[$__rate_interval])) by (http_route_name, le, http_request_method))",
       "legendFormat": ".90-{{http_request_method}}-{{http_route_name}}"
      },
      {
       "expr": "histogram_quantile(.50, sum(rate(ssv_cl_request_duration_seconds_bucket{cluster=~\"$cluster\", http_response_error_status_code=\"\"}[$__rate_interval])) by (http_route_name, le, http_request_method))",
       "legendFormat": ".50-{{http_request_method}}-{{http_route_name}}"
      }
     ]
    },
    {
     "title": "Consensus Layer Failed Request Count Per Method",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 620 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ssv_cl_request_duration_seconds_count{cluster=~\"$cluster\", http_response_error_status_code!=\"\"}) by (http_response_error_status_code, http_request_method, http_route_name, cluster)",
       "legendFormat": "{{http_response_error_status_code}}-{{http_request_method}}-{{http_route_name}} {{cluster}}"
      }
     ]
    }
   ]
  }
 ]
}