{
 "title": "Sui Validator Dashboard",
 "tags": [
  "sui",
  "fullnode"
 ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(highest_synced_checkpoint,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_commit_sync_local_index{env=\"$env\", project=\"sui\"} - consensus_commit_sync_quorum_index{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Consensus Sync Latency"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{env=\"$env\", project=\"sui\"} - last_certified_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Consensus Lag"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{env=\"$env\", project=\"sui\"} - last_executed_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Execution Lag"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(total_transaction_certificates{env=\"$env\", project=\"sui\"}[2m]))",
     "legendFormat": "Certificate Creation Rate"
    }
   ]
  },
  {
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n  scalar(\r\n    max(\r\n      consensus_last_committed_authority_round{env=\"$env\", project=\"sui\"}\r\n    )\r\n  )\r\n)\r\n-\r\nconsensus_last_committed_authority_round{\r\n  env=\"$env\", project=\"sui\",\r\n  authority=\"Encapsulate\"\r\n}",
     "legendFormat": "- Round Lag 🐢"
    },
    {
     "expr": "rate(consensus_last_committed_authority_round{env=\"$env\", project=\"sui\", authority=\"Encapsulate\"}[5m])",
     "legendFormat": "- Commit Rate🚀"
    },
    {
     "expr": "avg_over_time(consensus_reputation_scores{env=\"$env\", project=\"sui\", authority=\"Encapsulate\"}[5m])",
     "legendFormat": "- Avg Reputation 🌟"
    },
    {
     "expr": "sum(rate(consensus_proposed_blocks{env=\"$env\", project=\"sui\", force=\"false\"}[5m])) + sum(rate(consensus_proposed_blocks{env=\"$env\", project=\"sui\", force=\"true\"}[5m]))",
     "legendFormat": "- Proposals/s 🧱"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(consensus_block_commit_latency_bucket{env=\"$env\", project=\"sui\"}[5m])\r\n  )\r\n)",
     "legendFormat": "- Commit Lat (p95) ⏳"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(consensus_quorum_receive_latency_bucket{env=\"$env\", project=\"sui\"}[5m])\r\n  )\r\n)",
     "legendFormat": "- Quorum Lat (p95) ⏱️ "
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(authority_state_commit_certificate_latency_bucket{env=\"$env\", project=\"sui\"}[5m])\r\n  )\r\n)",
     "legendFormat": "- Cert Lat (p95) 🟪"
    },
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le) (\r\n    rate(authority_state_commit_certificate_latency_bucket{env=\"$env\", project=\"sui\"}[5m])\r\n  )\r\n)",
     "legendFormat": "- Cert Lat (p50) 🟨"
    },
    {
     "expr": "rate(consensus_threshold_clock_round{env=\"$env\", project=\"sui\"}[1m])",
     "legendFormat": "Round 1m Rate"
    },
    {
     "expr": "consensus_commit_sync_local_index{env=\"$env\", project=\"sui\"} - consensus_commit_sync_quorum_index{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Consensus Lag"
    }
   ]
  },
  {
   "title": "Sui Metrics",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(consensus_proposed_blocks{env=\"$env\", force=\"false\", project=\"sui\"}[5m])",
     "legendFormat": "Consensus Proposed Blocks Rate"
    },
    {
     "expr": "rate(validator_service_handle_certificate_non_consensus_latency_sum{env=\"$env\", project=\"sui\"}[5m]) / rate(validator_service_handle_certificate_non_consensus_latency_count{env=\"$env\", project=\"sui\"}[5m]) ",
     "legendFormat": "Execution Latency"
    },
    {
     "expr": "(avg_over_time(sequencing_estimated_latency{env=\"$env\", project=\"sui\"}[5m]))/1000",
     "legendFormat": "Consensus latency By Adapter "
    },
    {
     "expr": "rate(sequencing_certificate_latency_sum{position=\"0\",env=\"$env\", tx_type=\"owned_certificate\", project=\"sui\"}[5m]) / \nrate(sequencing_certificate_latency_count{position=\"0\",env=\"$env\", tx_type=\"owned_certificate\", project=\"sui\"}[5m]) ",
     "legendFormat": "Consensus Latency scoring {{tx_type}}"
    },
    {
     "expr": "rate(consensus_threshold_clock_round{env=\"$env\", project=\"sui\"}[1m])",
     "legendFormat": "Round 1m Rate"
    },
    {
     "expr": "sui_quinn_network_peers{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Consensus Peers"
    },
    {
     "expr": "(\n  scalar(\n    max(\n      consensus_last_committed_authority_round{env=\"$env\", project=\"sui\"}\n    )\n  )\n)\n-\nconsensus_last_committed_authority_round{\n  project=\"sui\",\n  env=\"$env\",\n  authority=\"Encapsulate (fka KingSuper)\"\n}",
     "legendFormat": "Round Lag "
    }
   ]
  },
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "num_input_objects_count{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Input Objects"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_transaction_certificates{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Total Txns"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates{env=\"$env\", project=\"sui\"}[30s])",
     "legendFormat": "Sync Speed TPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_transaction_effects{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Txns Effects"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_known_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Highest Checkpoint"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Sync'd Checkpoint"
    }
   ]
  },
  { "title": "Epoch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_epoch{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Current Epoch"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "epoch_total_duration{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Epoch Duration"
    }
   ]
  },
  { "title": "Validator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_executed_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Last Executed Checkpoint"
    },
    {
     "expr": "highest_synced_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Highest Synced Checkpoint"
    },
    {
     "expr": "highest_verified_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Highest Verified Checkpoint"
    },
    {
     "expr": "last_certified_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Last Certified Checkpoint"
    },
    {
     "expr": "highest_known_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Highest Known Checkpoint"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transactions_included_in_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Txns in Checkpoint"
    },
    {
     "expr": "total_transaction_orders{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Total Txns Orders"
    },
    {
     "expr": "total_handle_certificate_attempts{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Total Handle Certificate Attempts"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skipped_consensus_txns{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Skipped Consensus Txns"
    },
    {
     "expr": "total_signature_errors{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Total Signature Errors"
    }
   ]
  },
  { "title": "Checkpointing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "highest_known_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "highest_verified_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "last_executed_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Highest Synced Checkpoint ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Checkpoint Execution Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "(last_executed_checkpoint{env=\"$env\", project=\"sui\"} - highest_known_checkpoint{env=\"$env\", project=\"sui\"})",
     "legendFormat": "checkpoint execution backlog"
    }
   ]
  },
  {
   "title": "Checkpoint Synchronization Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "(highest_synced_checkpoint{env=\"$env\", project=\"sui\"} - highest_known_checkpoint{env=\"$env\", project=\"sui\"})",
     "legendFormat": "checkpoint execution backlog"
    }
   ]
  },
  {
   "title": "Last Executed Checkpoint (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "(rate(last_executed_checkpoint{env=\"$env\", project=\"sui\"}[2m]))",
     "legendFormat": "checkpoint execution backlog"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Certificates Created (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "(rate(total_transaction_certificates{env=\"$env\", project=\"sui\"}[2m]))",
     "legendFormat": "checkpoint execution backlog"
    }
   ]
  },
  {
   "title": "Certificate Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "(rate(validator_service_handle_certificate_non_consensus_latency_sum{env=\"$env\", project=\"sui\"}[5m])) / (rate(validator_service_handle_certificate_non_consensus_latency_count{env=\"$env\", project=\"sui\"}[2m]))",
     "legendFormat": "{{host}} owned_object"
    },
    {
     "expr": "(rate(validator_service_handle_certificate_consensus_latency_sum{env=\"$env\", project=\"sui\"}[5m])) / (rate(validator_service_handle_certificate_consensus_latency_count{env=\"$env\", project=\"sui\"}[2m]))",
     "legendFormat": "{{host}} shared_object"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Finalized TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "(rate(num_shared_obj_tx{env=\"$env\", project=\"sui\"}[2m]))",
     "legendFormat": "{{host}} shared_object"
    },
    {
     "expr": "(rate(num_shared_obj_tx{env=\"$env\", project=\"sui\"}[2m]))",
     "legendFormat": "{{host}} shared_object"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sui_quinn_network_peers{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  { "title": "Additional Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Inbound Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "rate(sui_inbound_request_latency_sum{env=\"$env\", project=\"sui\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Inbound Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "expr": "sui_inbound_requests{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Sync Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(highest_synced_checkpoint{env=\"$env\", project=\"sui\"} - highest_known_checkpoint{env=\"$env\", project=\"sui\"}, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sui_outbound_requests{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Outbound Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
   "targets": [
    {
     "expr": "rate(sui_outbound_request_latency_sum{env=\"$env\", project=\"sui\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Outbound Req. Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 99 },
   "targets": [
    {
     "expr": "sui_outbound_request_errors{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Sequencing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sequencing_certificate_success{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sequencing_certificate_failures{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sequencing_certificate_inflight{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sequencing_certificate_attempt{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Enqueued Certs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 108 },
   "targets": [
    {
     "expr": "transaction_manager_num_enqueued_certificates{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Voting Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
   "targets": [
    {
     "expr": "current_voting_right{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "User Key Comparison",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "user_key_comparison_count{env=\"$env\", project=\"sui\"}",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tally_channel_overflow{env=\"$env\", project=\"sui\"}",
     "legendFormat": "Tallying Scores by validator"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Info",
     "expr": "(sum by(level) (count_over_time({env=\"$env\", filename=\"/opt/sui/log/sui.log\"} |~ `(?i)inf` [$__auto])) * 100) / sum(count_over_time({env=\"$env\", filename=\"/opt/sui/log/sui.log\"} [$__auto]))",
     "legendFormat": "Info",
     "scenarioId": "INFO"
    },
    {
     "alias": "Error",
     "expr": "(sum by(level) (count_over_time({env=\"$env\", filename=\"/opt/sui/log/sui.log\"} |~ `(?i)err` [$__auto])) * 100) / sum(count_over_time({env=\"$env\", filename=\"/opt/sui/log/sui.log\"} [$__auto]))",
     "legendFormat": "Error",
     "scenarioId": "ERROR"
    },
    {
     "alias": "Warn",
     "expr": "(sum by(level) (count_over_time({env=\"$env\", filename=\"/opt/sui/log/sui.log\"} |~ `(?i)war` [$__auto])) * 100) / sum(count_over_time({env=\"$env\", filename=\"/opt/sui/log/sui.log\"} [$__auto]))",
     "legendFormat": "Warn",
     "scenarioId": "WARN"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{env=\"$env\", filename=\"/opt/sui/log/sui.log\"} != `DEBUG`"
    }
   ]
  }
 ]
}