{
 "title": "Sui Bridge Node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(current_bridge_voting_rights,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sui Bridge Metrics",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_action_executor_signing_queue_skipped_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}[5m])",
     "legendFormat": "Skipped actions in action executor signing queue"
    },
    {
     "expr": "rate(bridge_err_build_sui_transaction{env=\"$env\"}[5m])",
     "legendFormat": "Errors building sui transactions"
    },
    {
     "expr": "rate(bridge_err_sui_transaction_execution{env=\"$env\"}[5m])",
     "legendFormat": "Failures of sui transaction execution"
    },
    {
     "expr": "rate(bridge_err_sui_transaction_submission{env=\"$env\"}[5m])",
     "legendFormat": "Errors submitting sui transactions"
    }
   ]
  },
  { "title": "Bridge Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Build Version",
   "type": "stat",
   "description": "Shows the current build version of the SUI Bridge Node.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUI Chain ID",
   "type": "stat",
   "description": "Displays the chain identifier of the SUI Chain.",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "uptime{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Chain ID",
   "type": "stat",
   "description": "Displays the chain identifier of the Ethereum Chain.",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "uptime{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "ChainId"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "description": "Shows the current voting power distribution within the bridge committee, offering insights into the committee's decision-making influence and individual authority contributions.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(current_bridge_voting_rights{env=\"$env\", project=\"sui\", type=\"bridge\"}) \n/ \nsum(current_bridge_voting_rights{env=\"$env\", project=\"sui\", type=\"bridge\"}) \n* 100",
     "legendFormat": "Voting Power %"
    }
   ]
  },
  {
   "title": "Client Enabled",
   "type": "stat",
   "description": "Indicates whether the SUI Bridge client is enabled, showing 'true' or 'false' based on its current status.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridge Pause Status",
   "type": "stat",
   "description": "Displays the pause status for both ETH and SUI bridges.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(bridge_eth_bridge_paused{env=\"$env\", project=\"sui\", type=\"bridge\"})",
     "legendFormat": "eth"
    },
    {
     "expr": "max(bridge_sui_bridge_paused{env=\"$env\", project=\"sui\", type=\"bridge\"})",
     "legendFormat": "sui"
    }
   ]
  },
  {
   "title": "ETH Vault Balance",
   "type": "stat",
   "description": "Displays the current balance of the Ethereum vault for the SUI Bridge node. The balance is shown in ETH units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_eth_vault_balance{env=\"$env\", project=\"sui\", type=\"bridge\"}) / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT Vault Balance",
   "type": "stat",
   "description": "Displays the current balance of the USDT vault for the SUI Bridge node. The balance is shown in USDT units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_usdt_vault_balance{env=\"$env\", project=\"sui\", type=\"bridge\"}) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUI Gas Coin Balance",
   "type": "stat",
   "description": "Displays the current balance of the gas coin for the SUI Bridge node. The balance is shown in SUI units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_gas_coin_balance{env=\"$env\", project=\"sui\", type=\"bridge\"}) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Events Overview",
   "type": "stat",
   "description": "Provides an overview of key metrics for bridge event processing, including received, successful, and unrecognized events for both ETH and SUI networks. This panel offers insights into event volume, anomalies, and potential processing issues across different blockchain integrations.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_eth_watcher_received_events{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Received - ETH"
    },
    {
     "expr": "bridge_sui_watcher_received_events{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Received - SUI"
    },
    {
     "expr": "bridge_sui_watcher_unrecognized_events{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Unrecognized - SUI "
    },
    {
     "expr": "bridge_eth_watcher_unrecognized_events{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Unrecognized - ETH"
    }
   ]
  },
  {
   "title": "Events Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of received events in the Sui Watcher over time, providing insights into event processing throughput and anomaly detection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_eth_watcher_received_events{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "ETH"
    },
    {
     "expr": "rate(bridge_sui_watcher_received_events{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "SUI"
    }
   ]
  },
  {
   "title": "Unrecognized Events Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of unrecognized events in the Sui Watcher over time, providing insights into event processing throughput and anomaly detection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_sui_watcher_unrecognized_events{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "SUI"
    },
    {
     "expr": "rate(bridge_eth_watcher_unrecognized_events{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "ETH"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requests Overview",
   "type": "stat",
   "description": "Provides an aggregated overview of bridge requests, including total received, successfully processed (OK), and error requests. Data is categorized by request type, offering insights into system throughput and reliability.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_requests_received{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Received - {{type}}"
    },
    {
     "expr": "bridge_requests_ok{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Processed OK - {{type}}"
    },
    {
     "expr": "bridge_err_requests{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Error - {{type}}"
    }
   ]
  },
  {
   "title": "Inflight Requests Over Time",
   "type": "timeseries",
   "description": "Displays the number of inflight requests over time, categorized by request type, providing visibility into ongoing operations and potential bottlenecks in request handling.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(bridge_requests_inflight{env=\"$env\", project=\"sui\", type=\"bridge\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Received Requests Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of received requests over time, categorized by request type, providing visibility into ongoing operations and potential bottlenecks in request handling.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_requests_received{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "received - {{type}}"
    }
   ]
  },
  {
   "title": "Error Requests Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of error requests over time, categorized by request type.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_err_requests{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Actions Overview",
   "type": "stat",
   "description": "This panel provides an aggregated overview of bridge actions, including the total number of received, successfully processed (OK), and error requests. The data is categorized by request type, offering valuable insights into the system's throughput and reliability. It helps monitor the performance of different bridge action components, such as SUI -> ETH and ETH -> SUI data flows, allowing you to track received, processed, and skipped actions efficiently.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_action_executor_signing_queue_received_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Received"
    },
    {
     "expr": "bridge_action_executor_already_processed_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Processed"
    },
    {
     "expr": "bridge_action_executor_signing_queue_skipped_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "bridge_sui_watcher_received_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "SUI -> ETH"
    },
    {
     "expr": "bridge_eth_watcher_received_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "ETH -> SUI"
    }
   ]
  },
  {
   "title": "Action Executor Signing Queue Actions",
   "type": "timeseries",
   "description": "Shows key metrics for the Bridge Action Executor queue, including totals for received, skipped, and already processed actions, helping monitor queue performance and efficiency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bridge_action_executor_signing_queue_received_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "received {{host}} "
    },
    {
     "expr": "bridge_action_executor_already_processed_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "already processed {{host}} "
    },
    {
     "expr": "bridge_action_executor_signing_queue_skipped_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "skipped {{host}} "
    }
   ]
  },
  {
   "title": "Action Executor Execution Queue Actions",
   "type": "timeseries",
   "description": "Displays metrics for the execution queue in the Bridge Action Executor, including totals for received actions and actions skipped due to pausing, providing insights into queue activity and processing behavior.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bridge_action_executor_execution_queue_received_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "received {{host}} "
    },
    {
     "expr": "bridge_action_executor_execution_queue_skipped_actions_due_to_pausing{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "skipped processed {{host}} "
    }
   ]
  },
  {
   "title": "Action Executor Errors",
   "type": "timeseries",
   "description": "Displays error metrics for the Bridge Action Executor, including failures during Sui transaction execution, submission errors, and continuous submission failures, helping identify and address recurring issues.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bridge_err_build_sui_transaction{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "build sui tx {{host}} "
    },
    {
     "expr": "bridge_err_signature_aggregation{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "sig aggregation {{host}} "
    },
    {
     "expr": "bridge_err_sui_transaction_submission{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "submit sui tx {{host}} "
    },
    {
     "expr": "bridge_err_sui_transaction_submission_too_many_failures{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "submit sui tx too many failure {{host}} "
    },
    {
     "expr": "bridge_err_sui_transaction_execution{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "execute sui tx {{host}} "
    }
   ]
  },
  {
   "title": "Channel Inflight Items",
   "type": "timeseries",
   "description": "Displays the number of inflight items across monitored channels and the count of running tasks per callsite, providing visibility into system activity and task processing states.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(monitored_channel_inflight{env=\"$env\", project=\"sui\", type=\"bridge\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Transfer Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "rate(bridge_sui_watcher_received_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "sui -> eth {{host}}"
    },
    {
     "expr": "rate(bridge_eth_watcher_received_actions{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])",
     "legendFormat": "eth -> sui {{host}}"
    }
   ]
  },
  {
   "title": "Request Signer Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "targets": [
    {
     "expr": "bridge_signer_with_cache_miss{env=\"$env\", project=\"sui\", type=\"bridge\"} / (bridge_signer_with_cache_hit{env=\"$env\", project=\"sui\", type=\"bridge\"} + bridge_signer_with_cache_miss{env=\"$env\", project=\"sui\", type=\"bridge\"})",
     "legendFormat": "{{host}}  {{type}}"
    }
   ]
  },
  { "title": "ETH RPC Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "ETH RPC Query Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of Ethereum RPC queries processed over time, providing insights into query frequency and system workload trends.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(bridge_eth_rpc_queries{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ETH RPC Query Latency Distribution",
   "type": "timeseries",
   "description": "Displays the latency distribution for Ethereum RPC queries, categorized by method name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bridge_eth_rpc_queries_latency_bucket{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])) by (le, host, type))",
     "legendFormat": "{{host}} {{type}}"
    }
   ]
  },
  { "title": "Span Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Tracing Span Latency Distribution",
   "type": "timeseries",
   "description": "Displays the latency distribution for spans in the bridge node service, categorized by span names. Latency is measured in milliseconds and displayed across the 50th, 95th, and 99th percentiles.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tracing_span_latencies_bucket{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "95th percentile - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tracing_span_latencies_bucket{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "50th percentile - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tracing_span_latencies_bucket{env=\"$env\", project=\"sui\", type=\"bridge\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "99th percentile - {{span_name}}"
    }
   ]
  },
  {
   "title": "Tracing Span Average Latency",
   "type": "timeseries",
   "description": "Displays the average latency for spans in the bridge node service.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "tracing_span_latencies_sum{env=\"$env\", project=\"sui\", type=\"bridge\"} / tracing_span_latencies_count{env=\"$env\", project=\"sui\", type=\"bridge\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  }
 ]
}